### ISSUE TITLE
Jekyll is currently rendering the site. Please try again shortly

### ISSUE THREAD

**Issue by anshulsahni** [jamesward/jekyll-heroku#1]
After following the exact steps for deploying when I open in the heroku app link I get this message on screen `Jekyll is currently rendering the site. Please try again shortly`. No matter how much later you open the app it will show same message. Below is the screen shot
![screenshot from 2017-02-26 18 07 47](https://cloud.githubusercontent.com/assets/4351432/23339745/9246db04-fc4e-11e6-80c0-b2612e7dca1d.png)

**Comment by jamesward** [comment]
I updated everything and it is working again for me.  Can you redeploy the latest?

**Comment by anshulsahni** [comment]
nope same response,
this is the repository,
https://github.com/anshulsahni/undefined

**Comment by jamesward** [comment]
I see you have a repo already.  Ok, can you try these instructions:

1. Install [rbenv](https://github.com/rbenv/rbenv)
1. Create a `.ruby-version` file containing:
    ```
    2.4.0
    ```
1. Install Ruby via rbenv: `rbenv install`
1. Install Bundler: `gem install bundler`
1. Create a `Gemfile` containing:
    ```
    source 'https://rubygems.org'
    ruby '2.4.0'
    gem 'jekyll', '3.4.0'
    gem 'kramdown', '1.13.2'
    gem 'rack-jekyll', '0.5.0'
    gem 'rake', '12.0.0'
    gem 'puma', '3.7.1'
    gem 'yajl-ruby', '1.3.0'
    ```
1. Run: `bundle install`
1. Make sure it works locally: `bundle exec jekyll serve --watch`
1. Create a `Procfile` containing:
    ```
    web: bundle exec puma -t 8:32 -w 3 -p $PORT
    ```
1. Create a `Rakefile` containing:
    ```
    namespace :assets do
      task :precompile do
        puts `bundle exec jekyll build`
      end
    end
    ```
1. Add the following lines to your `_config.yml` file:
    ```
    gems: ['kramdown']
    exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
    ```
1. Add a `config.ru` containing:
    ```
    require 'rack/jekyll'
    require 'yaml'
    run Rack::Jekyll.new
    ```

Then you'll need to commit those files and push the repo to Heroku.  Let me know if it works.

**Comment by anshulsahni** [comment]
Just figured out the issue wasn't changes proposed by you but the bower dependencies, actually I am not a ruby guy just trying my hands on jekyll, so can you help me where should I put `bower install` in this diff related to deployment on heroku, currently I am committing all bower files and then deploying as a workaround solution

**Comment by anshulsahni** [comment]
Now this issue can be closed since it wasn't due to this piece of code but please do reply to my previous comment

**Comment by jamesward** [comment]
Cool.  Thanks for the update.  For Heroku it sounds like it might work if you have both the Node and the Ruby buildpacks.  By default only one buildpack is used but you can manually add a second via the Heroku dashboard or the Heroku CLI.
