### ISSUE TITLE
how to generate gemfile.lock 

### ISSUE THREAD

**Issue by innowebka** [jamesward/jekyll-heroku#2]
**for this theme** https://github.com/wowthemesnet/jekyll-theme-memoirs/ 
can please help me ?

**Comment by innowebka** [comment]
how to deploy to heroku ?

**Comment by jamesward** [comment]
The `gemfile.lock` is generated from Ruby Gems. You should be able to follow the normal Jekyll instructions for adding a theme.  Also you might find my blog helpful: https://jamesward.com/2014/09/24/jekyll-on-heroku/

For deploying to Heroku, just do the usual `git push heroku master` or setup auto-deploy from a GitHub repo.

**Comment by innowebka** [comment]
i tried but when i deploy to heroku it only shows me application error so can you generate a gemfile.lock for me ?

**Comment by innowebka** [comment]
and these are my files in my repo https://github.com/innowebka/16 check i dont know what error happend ?

**Comment by innowebka** [comment]
please i want to deploy it !!!❤️

**Comment by jamesward** [comment]
I honestly don't remember how all this stuff works.  I'm using Hugo now because of lots of pain with Jekyll.  So unfortunately I'm not going to be a big help.  Sorry!

**Comment by innowebka** [comment]
atleast can you check my files https://github.com/innowebka/16 whats wrong in my gemfile.lock ?

**Comment by jamesward** [comment]
I really don't know. :(  I've never done any Ruby.  Sorry, wish I could help!

**Comment by innowebka** [comment]
do have any tutorial on hugo ?

**Comment by jamesward** [comment]
I don't, but check out: https://github.com/roperzh/heroku-buildpack-hugo

**Comment by innowebka** [comment]
ive tried in my windows 10 but cant generate staic files out of hugo theme and theres no public folder so how to do it ?

and i followed this tutorial nothing happend https://levelup.gitconnected.com/build-a-personal-website-with-github-pages-and-hugo-6c68592204c7

can you generate staic file for me from this hugo theme https://github.com/themefisher/liva-hugo
